# battery reporting
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y
CONFIG_ZMK_BATTERY_REPORTING=y

# LED indicators
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_LED=y

# # uncomment to enable deep sleep
CONFIG_ZMK_IDLE_TIMEOUT=20000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
CONFIG_ZMK_PM_SOFT_OFF=y

# # uncomment to enable USB logging / debugging
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_KSCAN_LOG_LEVEL_DBG=y
# CONFIG_I2C_LOG_LEVEL_DBG=y

# Backlighting configuration
CONFIG_PWM=y
CONFIG_LED_PWM=y
#CONFIG_ZMK_BACKLIGHT=y
#CONFIG_ZMK_BACKLIGHT_LEVELS=5 
#CONFIG_ZMK_BACKLIGHT_BRT_START=100
#CONFIG_ZMK_BACKLIGHT_ON_START=y
#CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
CONFIG_ZMK_EXT_POWER=y


# ZMK Studio configuration
#-----------------------------------
CONFIG_ZMK_STUDIO=y

#Max allowable keymap layer display name. Type:int Default:20
#CONFIG_ZMK_KEYMAP_LAYER_NAME_MAX_LEN=20

#Enable/disable locking for ZMK Studio. Type:bool Default:y
CONFIG_ZMK_STUDIO_LOCKING=n

#Seconds of inactivity in ZMK Studio before automatically locking. Type:int Default:500
#CONFIG_ZMK_STUDIO_LOCK_IDLE_TIMEOUT_SEC=500

#Whether to automatically lock again whenever ZMK Studio disconnects from the device. Type:bool Default:y
#CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y

#Lower latency to request while ZMK Studio is active to improve responsiveness. Type:int Default:10
#CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=10

#Stack size for the dedicated RPC thread. Type:int Default:1800
#CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=1800

#Number of bytes available for buffering incoming messages. Type:int Default:30
#CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=30

#Number of bytes available for buffering outgoing messages. Type:int Default:64
#CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=64